version: '2.3'
services:
  cuxfilter:
    build: .
    ports:
      - 80:80
    # - 3000:3000
    #   - 3004:3004
    #   - 3005:3005
      - 3009:3009
    runtime: nvidia
    volumes:
      - /home/ajay/data:/usr/src/app/node_server/uploads
      - /home/ajay/cuxfilter/node_server/routes:/usr/src/app/node_server/routes
      - /home/ajay/cuxfilter/node_server/app.js:/usr/src/app/node_server/app.js
      - /home/ajay/cuxfilter/entrypoint.sh:/usr/src/app/entrypoint.sh
      - /home/ajay/cuxfilter/demos/GTC demo/public:/usr/src/app/demos/GTC demo/public
      - /home/ajay/cuxfilter/demos/GTC demo/server.js:/usr/src/app/demos/GTC demo/server.js
      - /home/ajay/cuxfilter/demos/GTC demo/webpack.config-dev.js:/usr/src/app/demos/GTC demo/webpack.config-dev.js
      - /home/ajay/cuxfilter/demos/GTC demo/webpack.config-prod.js:/usr/src/app/demos/GTC demo/webpack.config-prod.js
      - /home/ajay/cuxfilter/default:/etc/nginx/sites-enabled/default
      - /home/ajay/cuxfilter/demos/examples:/usr/src/app/demos/examples
    env_file:
      - config.env
    entrypoint: ["bash","./entrypoint.sh"]
